import Head from 'next/head';
import { ReactNode } from "react";
import styled from "styled-components";

const Container = styled.main`
    max-width: 768px;
    padding: 1rem;
    margin: 0 auto;
    height: 100%;
    width: 100%;
`

type LayoutProp = {
    children: ReactNode,
    title?: string
}

const Layout = ({children, title}: LayoutProp) => {
    return (
        <>
             <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
            {children}
            </Container>
        </>
    )
}

export default Layout